	questions: [
{question: "What is 2 + 2?",
answers: ["2", "1", "4", "8"],
rightAnswer: 2,
},
{question: "What is 2 + 3?",
answers: ["3", "5", "6", "1"],
rightAnswer: 1,
},
{question: "What is 1 + 2?",
answers: ["1", "8", "0", "3"],
rightAnswer: 3,
},
{question: "What is 1 + 0?",
answers: ["6", "7", "2", "1"],
rightAnswer: 3,
},
{question: "What is 1 + 1?",
answers: ["3", "2", "6", "0"],
rightAnswer: 1,
}
],